-- 코드를 입력하세요
SELECT c.AUTHOR_ID, c.AUTHOR_NAME, d.CATEGORY, SUM(d.TOTAL_PRICE) AS TOTAL_SALES
FROM AUTHOR c
JOIN (
    SELECT a.BOOK_ID, a.CATEGORY, a.AUTHOR_ID, a.PRICE * b.SALES AS TOTAL_PRICE
    FROM BOOK a
    JOIN (
        SELECT BOOK_ID, SUM(SALES) AS SALES
        FROM BOOK_SALES
        WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
        GROUP BY BOOK_ID
    ) b
    ON a.BOOK_ID = b.BOOK_ID
) d
ON c.AUTHOR_ID = d.AUTHOR_ID
GROUP BY c.AUTHOR_ID, c.AUTHOR_NAME, d.CATEGORY
ORDER BY c.AUTHOR_ID ASC, d.CATEGORY DESC
