-- 코드를 작성해주세요
SELECT PARENT.ID, 
       (SELECT COUNT(CHILD.PARENT_ID) 
        FROM ECOLI_DATA AS CHILD 
        WHERE CHILD.PARENT_ID = PARENT.ID) AS CHILD_COUNT
FROM ECOLI_DATA AS PARENT
ORDER BY PARENT.ID ASC;