
    
SELECT d.CAR_ID, d.CAR_TYPE, 
       ROUND(d.DAILY_FEE * (1 - (c.DISCOUNT_RATE / 100)) * 30, 0) AS FEE
FROM (
    SELECT a.CAR_ID, a.CAR_TYPE, a.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR a
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b
    ON a.CAR_ID = b.CAR_ID
    WHERE a.CAR_TYPE IN ('세단', 'SUV')
    GROUP BY a.CAR_ID
    HAVING SUM(
        CASE 
            WHEN b.CAR_ID IS NULL THEN 0
            WHEN b.START_DATE <= '2022-11-30' AND b.END_DATE >= '2022-11-01' THEN 1
            ELSE 0 
        END
    ) = 0
) AS d
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN c
ON d.CAR_TYPE = c.CAR_TYPE AND c.DURATION_TYPE = '30일 이상'
WHERE ROUND(d.DAILY_FEE * (1 - (c.DISCOUNT_RATE / 100)) * 30, 0) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, d.CAR_TYPE ASC, d.CAR_ID DESC;