-- 코드를 입력하세요
SELECT YEAR(a.SALES_DATE) AS YEAR, MONTH(a.SALES_DATE) AS MONTH, b.GENDER, COUNT(DISTINCT b.USER_ID) AS USERS
FROM ONLINE_SALE a
JOIN USER_INFO b
ON a.USER_ID = b.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR(a.SALES_DATE), MONTH(a.SALES_DATE), b.GENDER
ORDER BY YEAR ASC, MONTH ASC, b.GENDER ASC;