-- 코드를 입력하세요
# SELECT CAR_ID, 


# SELECT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY


SELECT CAR_ID, ROUND(AVG(DAY), 1) AS AVERAGE_DURATION
FROM (
    SELECT CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS DAY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) AS a
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;
