SELECT 
    YEAR(a.SALES_DATE)  AS YEAR, MONTH(a.SALES_DATE) AS MONTH, COUNT(DISTINCT a.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT a.USER_ID) / (
            SELECT COUNT(DISTINCT USER_ID) 
            FROM USER_INFO 
            WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'), 1) AS PURCHASED_RATIO
FROM ONLINE_SALE a
JOIN USER_INFO b
ON a.USER_ID = b.USER_ID AND b.JOINED BETWEEN '2021-01-01' AND '2021-12-31'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;