-- 코드를 입력하세요
SELECT a.PRODUCT_ID, a.PRODUCT_NAME, a.PRICE * SUM(b.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT a
JOIN FOOD_ORDER b
ON a.PRODUCT_ID = b.PRODUCT_ID
WHERE b.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC