-- 코드를 입력하세요
WITH RECURSIVE hours AS (
  SELECT 0 AS hour
  UNION ALL
  SELECT hour + 1 FROM hours WHERE hour < 23
)
SELECT hour AS HOUR, COUNT(DATETIME) AS COUNT
FROM hours a
LEFT JOIN ANIMAL_OUTS b ON a.hour = HOUR(b.DATETIME)
GROUP BY HOUR
ORDER BY HOUR;