-- 코드를 작성해주세요
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE ID IN (
    SELECT a.ID
    FROM DEVELOPERS a
    JOIN SKILLCODES b
    ON a.SKILL_CODE & b.CODE = b.CODE
    WHERE b.CATEGORY = "Front End"
)
ORDER BY ID ASC





