-- 코드를 작성해주세요

SELECT b.SCORE, a.EMP_NO, a.EMP_NAME, a.POSITION, a.EMAIL
FROM HR_EMPLOYEES a
JOIN (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
) b
ON a.EMP_NO = b.EMP_NO
GROUP BY a.EMP_NO
HAVING b.SCORE = (
    SELECT MAX(c.SCORE)
    FROM (
        SELECT SUM(SCORE) AS SCORE
        FROM HR_GRADE
        GROUP BY EMP_NO
    ) c
)

