-- 코드를 입력하세요
# SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT
# WHERE CATEGORY IN ("과자", "국", "김치", "식용유")
# GROUP BY CATEGORY
# ORDER BY MAX_PRICE DESC

SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT a
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
AND PRICE = (
      SELECT MAX(PRICE)
      FROM FOOD_PRODUCT
      WHERE CATEGORY = a.CATEGORY
)
ORDER BY MAX_PRICE DESC;